// Code generated by go generate; DO NOT EDIT.
package cmd

import "github.com/dansimau/huecfg/pkg/jsonutil"

func (c *apiRulesCreateCmd) Execute(args []string) error {
	if err := errorOnUnknownArgs(args); err != nil {
		return err
	}

	bridge := cmd.getHueAPI()

	data, err := userInputToJSON(c.Data)
	if err != nil {
		return err
	}

	respBytes, err := bridge.CreateRule(data)
	if err != nil {
		return err
	}

	if err := jsonutil.PrintBytes(respBytes); err != nil {
		return err
	}

	return nil
}
