// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"strings"

	"github.com/dansimau/huecfg/pkg/hue"
	"github.com/iancoleman/strcase"
)

func resourcelinksToGenericSlice(s []hue.ResourceLink) []interface{} {
	var res = make([]interface{}, len(s))
	for i, obj := range s {
		res[i] = obj
	}
	return res
}

type resourcelinksListCmd struct {
	Fields  string `long:"fields" description:"List of fields to include"`
	Reverse bool   `long:"reverse" description:"Reverse sort order"`
	Sort    string `long:"sort" description:"Field to sort by"`
}

func (c *resourcelinksListCmd) Execute(args []string) error {
	if err := errorOnUnknownArgs(args); err != nil {
		return err
	}

	bridge := cmd.getHue()

	resourcelinks, err := bridge.GetResourceLinks()
	if err != nil {
		return err
	}

	fields := resourcelinksDefaultFields
	if c.Fields != "" {
		fields = []string{}
		for _, fieldName := range strings.Split(c.Fields, ",") {
			fields = append(fields, resourcelinksHeaderTransform.TransformInput(fieldName))
		}
	}

	sortField := resourcelinksDefaultSortField
	if c.Sort != "" {
		sortField = strcase.ToCamel(resourcelinksHeaderTransform.TransformInput(c.Sort))
	}

	sortedresourcelinks, err := sortByField(resourcelinksToGenericSlice(resourcelinks), sortField, c.Reverse)
	if err != nil {
		return err
	}

	rows := [][]string{}

	headerRow := []string{}
	for _, fieldName := range fields {
		headerRow = append(headerRow, resourcelinksHeaderTransform.TransformOutput(fieldName))
	}
	rows = append(rows, headerRow)

	for _, light := range sortedresourcelinks {
		row := []string{}

		for _, field := range fields {
			v, err := lookupField(light, field)
			if err != nil {
				return err
			}

			row = append(row, resourcelinksFieldTransform.TransformOutput(field, reflectValueToString(v)))
		}

		rows = append(rows, row)
	}

	printTable(rows)

	return nil
}
