// Code generated by go generate; DO NOT EDIT.
package cmd

import (
	"strings"

	"github.com/dansimau/huecfg/pkg/huev1"
	"github.com/iancoleman/strcase"
)

func schedulesToGenericSlice(s []huev1.Schedule) []interface{} {
	var res = make([]interface{}, len(s))
	for i, obj := range s {
		res[i] = obj
	}
	return res
}

type schedulesListCmd struct {
	Fields  string `long:"fields" description:"List of fields to include"`
	Reverse bool   `long:"reverse" description:"Reverse sort order"`
	Sort    string `long:"sort" description:"Field to sort by"`
}

func (c *schedulesListCmd) Execute(args []string) error {
	if err := errorOnUnknownArgs(args); err != nil {
		return err
	}

	bridge := cmd.getHue()

	schedules, err := bridge.GetSchedules()
	if err != nil {
		return err
	}

	fields := schedulesDefaultFields
	if c.Fields != "" {
		fields = []string{}
		for _, fieldName := range strings.Split(c.Fields, ",") {
			fields = append(fields, schedulesHeaderTransform.TransformInput(fieldName))
		}
	}

	sortField := schedulesDefaultSortField
	if c.Sort != "" {
		sortField = strcase.ToCamel(schedulesHeaderTransform.TransformInput(c.Sort))
	}

	sortedschedules, err := sortByField(schedulesToGenericSlice(schedules), sortField, c.Reverse)
	if err != nil {
		return err
	}

	rows := [][]string{}

	headerRow := []string{}
	for _, fieldName := range fields {
		headerRow = append(headerRow, schedulesHeaderTransform.TransformOutput(fieldName))
	}
	rows = append(rows, headerRow)

	for _, light := range sortedschedules {
		row := []string{}

		for _, field := range fields {
			v, err := lookupField(light, field)
			if err != nil {
				return err
			}

			row = append(row, schedulesFieldTransform.TransformOutput(field, reflectValueToString(v)))
		}

		rows = append(rows, row)
	}

	printTable(rows)

	return nil
}
